name: Build
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:
permissions:
  contents: write
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read
jobs:
  compile-shobuarch:
    name: go_build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - name: Checkout
        uses: actions/checkout@master
        
      - name: Set up Go
        uses: actions/setup-go@master
        with:
         go-version: 1.18
        
      - name: Build
        run: go build -o ./.build/ -v ./...
        
      - name: Test
        run: go test -v ./...
        
      # - name: Upload Artifact
      #   uses: actions/upload-artifact@master
      #   with:
      #     name: ShobuArch
      #     path: ./.build/
          
      - name: Commit Build
        run: |
         git config --global user.name '${{ secrets.GIT_USER }}'
         git config --global user.email '${{ secrets.GIT_EMAIL }}'
         git remote set-url --push origin https://x-access-token:${{ secrets.ShobuArch_Builder }}@github.com/ShobuPrime/ShobuArch.git
         git add -A
         git commit -am "Automated Build"
         git push origin main
 
